// <auto-generated />
namespace DataAccessLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Edit_SenderID_To_SenderMail_And_Edit_RecieverID_To_RecieverMail : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Edit_SenderID_To_SenderMail_And_Edit_RecieverID_To_RecieverMail));
        
        string IMigrationMetadata.Id
        {
            get { return "202109111945266_Edit_SenderID_To_SenderMail_And_Edit_RecieverID_To_RecieverMail"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
