// <auto-generated />
namespace DataAccessLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class FileName_in_Message_Table : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FileName_in_Message_Table));
        
        string IMigrationMetadata.Id
        {
            get { return "202109141015500_FileName_in_Message_Table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
